'use client';

import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { supabase } from '@/lib/supabaseClient';

interface Vehicle {
  id: string;
  name: string;
  max_payload_kg: number;
  base_rate: number;
  rate_per_mile: number;
  co2_per_mile_g: number;
  is_active: boolean;
}

export function Footer() {
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [loading, setLoading] = useState(true);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    async function fetchVehicles() {
      try {
        const { data, error } = await supabase
          .from('vehicles')
          .select('id, name, max_payload_kg, base_rate, rate_per_mile, co2_per_mile_g, is_active')
          .eq('is_active', true)
          .order('max_payload_kg', { ascending: true });

        if (error) throw error;
        if (data && data.length > 0) {
          setVehicles(data);
        } else {
          // Fallback to static insert data if DB is empty
          setVehicles([
            { id: '1', name: 'Small Express Van', max_payload_kg: 500, base_rate: 25.00, rate_per_mile: 1.20, co2_per_mile_g: 140, is_active: true },
            { id: '2', name: 'Midsized Transit Van', max_payload_kg: 1200, base_rate: 45.00, rate_per_mile: 1.50, co2_per_mile_g: 195, is_active: true },
            { id: '3', name: 'Luton Box Van (Tail Lift)', max_payload_kg: 1600, base_rate: 65.00, rate_per_mile: 1.80, co2_per_mile_g: 240, is_active: true },
            { id: '4', name: '7.5 Tonne Rigid Truck', max_payload_kg: 3000, base_rate: 110.00, rate_per_mile: 2.20, co2_per_mile_g: 420, is_active: true },
            { id: '5', name: '18 Tonne Heavy Freight', max_payload_kg: 9000, base_rate: 180.00, rate_per_mile: 2.80, co2_per_mile_g: 680, is_active: true },
            { id: '6', name: '40ft Articulated Lorry', max_payload_kg: 26000, base_rate: 250.00, rate_per_mile: 3.50, co2_per_mile_g: 910, is_active: true },
          ]);
        }
      } catch (err) {
        // Fallback gracefully on query error
        setVehicles([
          { id: '1', name: 'Small Express Van', max_payload_kg: 500, base_rate: 25.00, rate_per_mile: 1.20, co2_per_mile_g: 140, is_active: true },
          { id: '2', name: 'Midsized Transit Van', max_payload_kg: 1200, base_rate: 45.00, rate_per_mile: 1.50, co2_per_mile_g: 195, is_active: true },
          { id: '3', name: 'Luton Box Van (Tail Lift)', max_payload_kg: 1600, base_rate: 65.00, rate_per_mile: 1.80, co2_per_mile_g: 240, is_active: true },
          { id: '4', name: '7.5 Tonne Rigid Truck', max_payload_kg: 3000, base_rate: 110.00, rate_per_mile: 2.20, co2_per_mile_g: 420, is_active: true },
        ]);
      } finally {
        setLoading(false);
      }
    }
    fetchVehicles();
  }, []);

  const faqs = [
    {
      q: "What areas do you collect from?",
      a: "Our primary dispatch depot is in Cardiff, South Wales. We guarantee collection within 60 minutes for any location in Cardiff, Newport, and the surrounding South Wales valleys. Through our trusted logistics network partners, we coordinate collections nationwide across the UK."
    },
    {
      q: "How is the carbon footprint calculated?",
      a: "We use a mathematical calculation model based on the exact road distance between your postcodes multiplied by the verified CO2 emissions coefficient of your selected vehicle class. This provides a highly accurate estimate of the emissions generated by your specific delivery."
    },
    {
      q: "What is a 'dedicated' courier service?",
      a: "Dedicated courier service means that the vehicle assigned to your shipment is used exclusively for your cargo. Once collected, the vehicle travels directly to the delivery destination without stopping to load other customers' goods or passing through regional sorting hubs."
    },
    {
      q: "Can I set up a monthly credit account?",
      a: "Yes. We offer 30-day net credit accounts for corporate clients who ship regularly. To set up an account, please submit a general enquiry through our Contact Page or contact our accounts team directly at corporate@logitechtransport.co.uk."
    }
  ];

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <footer className="bg-[#121212] text-[#F8F9FA] border-t-4 border-[#1B4332] pt-16 pb-8 px-4 sm:px-6 lg:px-8 font-sans relative overflow-hidden">
      {/* Decorative Forest Green Accent Background Blob */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-[#1B4332] opacity-10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-80 h-80 bg-[#FFD166] opacity-5 rounded-full blur-3xl pointer-events-none" />

      <div className="max-w-7xl mx-auto relative z-10">
        {/* Top Header Grid: Brand Identity & Live Trust Badges */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 pb-12 border-b border-[#1B4332]/50">
          <div className="lg:col-span-6 space-y-4">
            <div className="flex items-center space-x-3">
              <span className="bg-[#FFD166] text-[#121212] font-black tracking-tight text-xl px-3 py-1 rounded">
                LOGITECH
              </span>
              <span className="text-white font-bold tracking-widest text-lg">
                TRANSPORT
              </span>
            </div>
            <p className="text-xs uppercase tracking-widest text-[#FFD166] font-bold">
              CARDIFF BORN, UK WIDE
            </p>
            <p className="text-sm text-[#F8F9FA]/80 max-w-lg leading-relaxed">
              Rapid, carbon-audited transport solutions across the United Kingdom. From same-day urgent courier dispatch to heavy multi-pallet distribution, we deliver operational precision with complete environmental accountability.
            </p>
          </div>

          <div className="lg:col-span-6 grid grid-cols-1 sm:grid-cols-3 gap-4 lg:self-center">
            <div className="bg-[#1E1E1E] p-4 rounded-lg border border-[#1B4332] flex flex-col justify-between">
              <span className="text-[#FFD166] text-xs font-bold uppercase tracking-wider block mb-1">
                Goods In Transit
              </span>
              <span className="text-sm font-semibold text-white">Fully Insured</span>
              <span className="text-xs text-[#F8F9FA]/60 mt-1">Up to £50,000 protection</span>
            </div>
            <div className="bg-[#1E1E1E] p-4 rounded-lg border border-[#1B4332] flex flex-col justify-between">
              <span className="text-[#FFD166] text-xs font-bold uppercase tracking-wider block mb-1">
                RHA Certified
              </span>
              <span className="text-sm font-semibold text-white">Active Member</span>
              <span className="text-xs text-[#F8F9FA]/60 mt-1">ID: RHA-883921-WA</span>
            </div>
            <div className="bg-[#1E1E1E] p-4 rounded-lg border border-[#1B4332] flex flex-col justify-between">
              <span className="text-[#FFD166] text-xs font-bold uppercase tracking-wider block mb-1">
                GPS Tracking
              </span>
              <span className="text-sm font-semibold text-white">Real-Time Data</span>
              <span className="text-xs text-[#F8F9FA]/60 mt-1">Live telemetry on all runs</span>
            </div>
          </div>
        </div>

        {/* Main Footer Directory Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-12 py-12">
          
          {/* Column 1: Navigation Links */}
          <div className="lg:col-span-2 space-y-4">
            <h3 className="text-sm font-black uppercase tracking-wider text-[#FFD166] border-b border-[#1B4332] pb-2">
              Our Services
            </h3>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="#services" className="text-[#F8F9FA]/70 hover:text-[#FFD166] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FFD166] rounded px-1">
                  Same-Day Urgent Courier
                </a>
              </li>
              <li>
                <a href="#services" className="text-[#F8F9FA]/70 hover:text-[#FFD166] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FFD166] rounded px-1">
                  Heavy & Pallet Freight
                </a>
              </li>
              <li>
                <a href="#services" className="text-[#F8F9FA]/70 hover:text-[#FFD166] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FFD166] rounded px-1">
                  Scheduled & Contract Logistics
                </a>
              </li>
              <li>
                <a href="#services" className="text-[#F8F9FA]/70 hover:text-[#FFD166] transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FFD166] rounded px-1">
                  Eco-Optimized Distribution
                </a>
              </li>
              <li>
                <a href="#quote-calculator" className="inline-block mt-4 bg-[#1B4332] hover:bg-[#1B4332]/80 text-white font-bold py-2 px-4 rounded text-xs transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FFD166]">
                  Instant Price Estimator
                </a>
              </li>
            </ul>
          </div>

          {/* Column 2: Live Database Fleet Overview */}
          <div className="lg:col-span-4 space-y-4">
            <h3 className="text-sm font-black uppercase tracking-wider text-[#FFD166] border-b border-[#1B4332] pb-2 flex items-center justify-between">
              <span>Active Green Fleet</span>
              <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-[#1B4332] text-[#FFD166]">
                Live CO2 Data
              </span>
            </h3>
            {loading ? (
              <div className="space-y-3">
                {[1, 2, 3].map((n) => (
                  <div key={n} className="animate-pulse h-8 bg-[#1E1E1E] rounded" />
                ))}
              </div>
            ) : (
              <div className="space-y-2">
                <p className="text-xs text-[#F8F9FA]/60 italic mb-2">
                  Direct specifications of active vehicles operating from our Cardiff hub:
                </p>
                <div className="grid grid-cols-1 gap-2 max-h-60 overflow-y-auto pr-2 custom-scrollbar">
                  {vehicles.map((v) => (
                    <div
                      key={v.id}
                      className="bg-[#1E1E1E]/80 p-2 rounded border border-[#1B4332]/40 hover:border-[#FFD166]/50 transition-colors flex justify-between items-center text-xs"
                    >
                      <div>
                        <span className="font-semibold text-white block">{v.name}</span>
                        <span className="text-[#F8F9FA]/60">Max Payload: {v.max_payload_kg.toLocaleString()} kg</span>
                      </div>
                      <div className="text-right">
                        <span className="text-[#FFD166] font-mono block">{v.co2_per_mile_g}g CO₂/mi</span>
                        <span className="text-[#F8F9FA]/40 text-[10px]">Base Fee: £{Number(v.base_rate).toFixed(2)}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Column 3: Mini FAQ Accordion */}
          <div className="lg:col-span-3 space-y-4">
            <h3 className="text-sm font-black uppercase tracking-wider text-[#FFD166] border-b border-[#1B4332] pb-2">
              Frequently Asked Questions
            </h3>
            <div className="space-y-2">
              {faqs.map((faq, idx) => {
                const isOpen = openFaq === idx;
                return (
                  <div key={idx} className="border-b border-[#1E1E1E] last:border-none pb-2">
                    <button
                      onClick={() => toggleFaq(idx)}
                      className="w-full text-left font-semibold text-xs text-white hover:text-[#FFD166] flex justify-between items-start py-1 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#FFD166] rounded"
                      aria-expanded={isOpen}
                    >
                      <span className="pr-2">{faq.q}</span>
                      <span className="text-[#FFD166] font-mono">{isOpen ? '−' : '+'}</span>
                    </button>
                    <AnimatePresence initial={false}>
                      {isOpen && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.2 }}
                          className="overflow-hidden"
                        >
                          <p className="text-xs text-[#F8F9FA]/70 pt-1 leading-relaxed pl-1 border-l-2 border-[#1B4332] mt-1">
                            {faq.a}
                          </p>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Column 4: HQ & Dispatch Control Hub */}
          <div className="lg:col-span-3 space-y-4">
            <h3 className="text-sm font-black uppercase tracking-wider text-[#FFD166] border-b border-[#1B4332] pb-2">
              Cardiff Headquarters
            </h3>
            <div className="text-xs space-y-3 text-[#F8F9FA]/80">
              <div>
                <p className="font-bold text-white text-sm">Logitech Transport HQ</p>
                <p>Unit 4, East Tyndall Street Industrial Estate</p>
                <p>Cardiff, South Wales</p>
                <p className="text-[#FFD166] font-semibold">CF24 5SD</p>
              </div>

              <div className="space-y-1">
                <p>
                  <span className="text-[#FFD166] font-semibold">Main Dispatch:</span>{' '}
                  <a href="tel:+442920112233" className="hover:text-white underline">
                    +44 (0) 29 2011 2233
                  </a>{' '}
                  <span className="text-emerald-500 font-bold">(24/7/365)</span>
                </p>
                <p>
                  <span className="text-[#FFD166] font-semibold">Accounts Office:</span>{' '}
                  <a href="tel:+442920112234" className="hover:text-white underline">
                    +44 (0) 29 2011 2234
                  </a>
                </p>
              </div>

              <div className="space-y-1 pt-1">
                <p className="truncate">
                  <span className="text-[#FFD166] font-semibold">Bookings:</span>{' '}
                  <a href="mailto:dispatch@logitechtransport.co.uk" className="hover:text-white underline">
                    dispatch@logitechtransport.co.uk
                  </a>
                </p>
                <p className="truncate">
                  <span className="text-[#FFD166] font-semibold">Corporate:</span>{' '}
                  <a href="mailto:corporate@logitechtransport.co.uk" className="hover:text-white underline">
                    corporate@logitechtransport.co.uk
                  </a>
                </p>
              </div>
            </div>
          </div>

        </div>

        {/* Environmental Statement Callout */}
        <div className="bg-[#1B4332]/40 border border-[#1B4332] rounded-xl p-6 my-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="space-y-1 text-center md:text-left">
            <h4 className="text-sm font-black text-[#FFD166] uppercase tracking-wider">
              Ready to reduce your corporate carbon footprint?
            </h4>
            <p className="text-xs text-[#F8F9FA]/80 max-w-2xl">
              We actively optimize routes via dynamic machine learning to eliminate empty back-haul miles, saving up to 22% in emissions compared to legacy freight networks. Get your instant CO₂ audit statement with every single run.
            </p>
          </div>
          <a
            href="#quote-calculator"
            className="bg-[#FFD166] hover:bg-[#F4D35E] text-[#121212] font-black text-xs uppercase px-6 py-3 rounded-md transition-colors whitespace-nowrap focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FFD166]"
          >
            Calculate Carbon Savings
          </a>
        </div>

        {/* Bottom Bar: Copyright, System Status & Back to Top */}
        <div className="border-t border-[#1E1E1E] pt-8 mt-8 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-[#F8F9FA]/60">
          <div className="flex flex-col sm:flex-row items-center gap-2 sm:gap-4 text-center sm:text-left">
            <span>© 2024 Logitech Transport. All rights reserved.</span>
            <span className="hidden sm:inline text-[#1B4332]">•</span>
            <span>RHA Conditions of Carriage Apply.</span>
            <span className="hidden sm:inline text-[#1B4332]">•</span>
            <a href="#contact" className="hover:text-[#FFD166] underline">
              Corporate Account Enquiries
            </a>
          </div>

          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2 bg-[#1E1E1E] px-3 py-1 rounded-full border border-[#1B4332]/40">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-[11px] font-mono text-white/90">Dispatch Status: Normal</span>
            </div>

            <button
              onClick={scrollToTop}
              className="bg-[#1E1E1E] hover:bg-[#1B4332] text-[#F8F9FA] hover:text-[#FFD166] p-2 rounded-full border border-[#1B4332]/40 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FFD166]"
              aria-label="Back to top"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2.5}
              >
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 10l7-7m0 0l7 7m-7-7v18" />
              </svg>
            </button>
          </div>
        </div>

      </div>
    </footer>
  );
}